### ISSUE TITLE
geOrchestra version

### ISSUE THREAD

**Issue by pmauduit** [georchestra/ansible#100]
As discussed this morning on IRC, for now this repository is making use of branches to setup either master or maintenance versions of geOr:
https://github.com/georchestra/ansible/branches

We could stick to the master branch, and use a variable instead to switch to the expected georchestra version. The only place where one can find the version being set is here:
https://github.com/georchestra/ansible/blob/22.0.x/playbooks/georchestra.yml#L84

And the diff between master and 22.0.x seems pretty limited:
https://github.com/georchestra/ansible/compare/master...22.0.x

**Comment by landryb** [comment]
i fully support the idea :)
