### ISSUE TITLE
SetEnv no-gzip on

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/ansible#24]
Is there any reason why this is so ?
https://github.com/landryb/georchestra-ansible/blob/master/roles/apache/templates/global.conf.j2#L10

The doc says to load the deflate module and to 
```
AddOutputFilterByType DEFLATE text/html text/plain text/xml application/xml text/css text/javascript application/javascript
```

**Comment by landryb** [comment]
Probably cargo-culted-copy-pasted. Will disappear with apache2.
