### ISSUE TITLE
mapfishapp db services are broken

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/ansible#26]
2016-02-14 14:27:29 ws [ERROR] org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "www-data")

**Comment by fvanderbiest** [comment]
Still broken...

**Comment by fvanderbiest** [comment]
in mapfishapp's `WEB-INF/ws-servlet.xml`:
```
    <bean id="pgpool" class="org.georchestra.mapfishapp.model.ConnectionPool" init-method="init">
        <property name="jdbcUrl" value="jdbc:postgresql://localhost:5432/georchestra?user=www-data&amp;password=www-data" /> 
    </bean>
```
in the datadir:
```
jdbcUrl=jdbc:postgresql://localhost:5432/georchestra?user=www-data&password=www-data
```

But my playbook says:
```
      db: {
        name: georchestra,
        user: georchestra,
        pass: georchestra
      },
```

Strange. 
Gonna destroy the machine and recreate it.

**Comment by landryb** [comment]
argh, in my last commit 'fixing' jdbcUrl i forgot to template mapfishapp.properties. my bad, will fix (along ws-servlet.xml too, but that'd be better to have the info in a single place...)
