### ISSUE TITLE
use the same ports for connectors as the official documentation

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/ansible#35]
eg:
 * 8180 for tomcat-proxycas
 * 8280 for georchestra
 * 8380 for geoserver

**Comment by landryb** [comment]
Well, there's only georchestra and geoserver ports to invert then..

**Comment by fvanderbiest** [comment]
Fixed with https://github.com/georchestra/ansible/commit/704e38e574635be56e187d1af5918ff6be732415 but ports are not templated, this is handled by #38

**Comment by landryb** [comment]
#38 merged
