### ISSUE TITLE
logs_basedir does not seem to be enforced

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/ansible#36]
As of today, setting `logs_basedir: /srv/log` has no effect: logs go to `/tmp`

**Comment by landryb** [comment]
Well, if you deploy all the roles/georchestra/templates (https://github.com/georchestra/ansible/blob/master/roles/georchestra/tasks/config.yml#L12), roles/tomcat/templates files (https://github.com/georchestra/ansible/blob/master/roles/tomcat/tasks/instance.yml#L62), and the tomcat/webapps are restarted, logs_basedir is in use..

**Comment by landryb** [comment]
at first start of webapps, and before the config is templated/tomcat restarted, granted, some stuff can go to /tmp ..

**Comment by fvanderbiest** [comment]
This is strange because the log4j files I had a look at yesterday in my newly generated VM mentioned `/tmp`

**Comment by landryb** [comment]
what does `grep -r /srv/log /etc/georchestra` say ?

**Comment by fvanderbiest** [comment]
It says too little sleep for me yesterday ;-)
