### ISSUE TITLE
apache 000-default site has to be disabled because it overlaps the georchestra site

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/ansible#37]
To make apache work again I had to run:

```
vagrant@debian-jessie:~$ sudo a2dissite 000-default
Site 000-default disabled.
To activate the new configuration, you need to run:
  service apache2 reload
```

Maybe a side effect of using

```
$ cat /etc/debian_version 
8.4
```

**Comment by landryb** [comment]
Can we just kill apache instead ? :)

**Comment by fvanderbiest** [comment]
Easier said than done !

**Comment by landryb** [comment]
Well, what's so special about the rules here ? If i look at https://github.com/georchestra/georchestra/blob/15.12/doc/setup/apache.md : 
  * it's 'list all subdirs' which could be reduced to 'common stuff' in nginx, + location blocks for special cases - seems only CORS for /geoserver/
  * force-redirect 301 to https if http
  * rewrite /foo to /foo/
  * deny access to /proxy/ if the referer is not the ids
  * DEFLATE for static files (what's that ? gzip by default ?)
  * what does ` Require all granted` do ?

is there more than this ? The mod_jk stuff was removed a while ago..

**Comment by landryb** [comment]
I think this issue can be closed, as 000-default has always been disabled by the task here: https://github.com/georchestra/ansible/blob/master/roles/apache/tasks/main.yml#L19
