### ISSUE TITLE
Update to work with geOrchestra master

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/ansible#42]
In the main README, I added the following sentence: "Very recently, in June 2016, developments (which happen in geOrchestra's master branch for the 16.12 release) led to breaking changes in the LDAP data model, which, to date, have not been ported to this repository. There's currently no guarantee that the security system works if you deploy a geOrchestra SDI with this ansible recipe for the moment."
See https://github.com/georchestra/georchestra/issues/1415

Maybe it's also time for branches in the current repository ?

**Comment by fvanderbiest** [comment]
Sorry I did not see your email on the list ...

Juste pour info, j'ai pris un peu de temps pour mettre à jour https://github.com/georchestra/ansible suite aux changements d'arborescence du LDAP (https://github.com/georchestra/georchestra//issues/1428 et https://github.com/georchestra/georchestra/issues/1415)

La migration d'une IDS existante avec l'ancien layout ou=groups 'devrait' aussi marcher (ie les bouts de l'arborescence devraient être renommés avec les nouveaux noms, cf https://github.com/georchestra/ansible/blob/master/roles/openldap/tasks/migrate_groups.yml)

Le déploiement des paquets debian venant de la CI (et de la branche master) devrait donc de nouveau produire une IDS complétement fonctionnelle - n'hésitez pas a me répondre ici si vous avez des problèmes liés à ce point.

**Comment by landryb** [comment]
> Maybe it's also time for branches in the current repository ?

Sure, once we have debian packages for branches :)

**Comment by pmauduit** [comment]
> Sure, once we have debian packages for branches :)

There is just a jenkins build to re-activate and there you have
