### ISSUE TITLE
unarchive fails on ubuntu, but succeeds on centos, with a zip file and remote_src

### ISSUE THREAD

**Issue by yinonby** [georchestra/ansible#45]
to reproduce:
target must be centos, ansible runs from ubuntu
place a .zip file on the target
verify unzip is installed on the target
call unarchive with remote_src: yes

will get failure:
fatal: [c6-bl-2]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to find handler for \"/tmp/ansible-tmp-1490881579.04-112291742753076/source\". Make sure the required command
 installed."}

**Comment by landryb** [comment]
I dont understand what you mean... is it specific to a task failing in our playbook ?

**Comment by yinonby** [comment]
This task is not supposed to fail. When I run it from centos to centos, it doesn't fail. When running from ubuntu to centos, it does [fail]. There are also many other problems with ubuntu which makes me think it is not stable. for example, when using "any_error_fatal: true" on ubuntu, the playbook keeps going after errors. on centos it works fine.

**Comment by landryb** [comment]
Which task are you talk about in particular ?

Also, i never used nor ubuntu or centos, either as target or source for ansible. Only debian.
