### ISSUE TITLE
ansible book not running on xubuntu 14.04.05

### ISSUE THREAD

**Issue by gustavopalminha** [georchestra/ansible#46]
Using xubuntu 14.04.5 LTS and after downloading the zip repo the ansible playbook did not run.

I used sudo with the default command and it didn't work.

The ansible book georchestra.yml was updated, mainly the hosts to localhost or local ip 127.0.0.1 but it returned the attached error triggered by openldap.

georchestrra.yml:
[georchestra.txt](https://github.com/georchestra/ansible/files/1009315/georchestra.txt)

ansible terminal log:
[ansible.txt](https://github.com/georchestra/ansible/files/1009306/ansible.txt)

**Comment by fvanderbiest** [comment]
I think this playbook is only meant to run on Debian Jessie.
Maybe it should be more explicit in the README. ping @landryb

**Comment by landryb** [comment]
Well it's been *only* tested on jessie, as already stated in the README. I'm open to pull requests to support/debug other environments.
