### ISSUE TITLE
Ansible Debian 9 vers Debian 8

### ISSUE THREAD

**Issue by pierrejego** [georchestra/ansible#47]
Hello,
just to let you know. 
I have used this playbook to install from a debian8 to a debian8 server and it worked perfectly.

I am know lanching ansible playbook from a Debian 9 to install georchestra on a remote debian8 server.
I had several issues that I'd like to share, to keep a trace. 

First, default version of Ansible on debian 9, is not compatible with the georchestra playbook. Some module attributes have changed in recent Ansible version.
I have reinstall Ansible using https://linuxconfig.org/ansible-installation-on-debian-9-stretch-linux-from-source to be able to change version. Be carefull python version need as well to be changed via pip.

Then I didn't manage to make playbook working with a another user than root. Each time the ssh connection failed.
I have create an ssh passphrase with other users, but ansible failed to connect each time even in sudo.  
If i add -vvvv to view the error we can see, there is no user set for connection

`
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<192.168.1.13> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.1.13> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/pierre/.ansible/cp/ansible-ssh-%h-%p-%r 192.168.1.13 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1509962416.62-118707537641112 `" && echo ansible-tmp-1509962416.62-118707537641112="` echo ~/.ansible/tmp/ansible-tmp-1509962416.62-118707537641112 `" ) && sleep 0'"'"''
`

Using root user, it works and we can see

`<192.168.1.13> ESTABLISH SSH CONNECTION FOR USER: Root`

Now, I have an other issue, when it try to install slap, it fails
I am working on the solution, I think it's because of python version. Here is the trace, it seems to be on unknow attribute  SSL_ST_INIT for installation.

`failed: [mygeorchestra] (item=[u'git', u'slapd', u'ldap-utils']) => {
    "failed": true, 
    "invocation": {
        "module_name": "apt"
    }, 
    "item": [
        "git", 
        "slapd", 
        "ldap-utils"
    ], 
    "module_stderr": "OpenSSH_7.4p1 Debian-10+deb9u1, OpenSSL 1.0.2l  25 May 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 6879\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 192.168.1.13 closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_t4uEl_/ansible_module_apt.py\", line 208, in <module>\r\n    from ansible.module_utils.urls import fetch_url\r\n  File \"/tmp/ansible_t4uEl_/ansible_modlib.zip/ansible/module_utils/urls.py\", line 150, in <module>\r\n  File \"/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py\", line 55, in <module>\r\n    import OpenSSL.SSL\r\n  File \"/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py\", line 8, in <module>\r\n    from OpenSSL import rand, crypto, SSL\r\n  File \"/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py\", line 105, in <module>\r\n    SSL_ST_INIT = _lib.SSL_ST_INIT\r\nAttributeError: 'module' object has no attribute 'SSL_ST_INIT'\r\n", 
    "msg": "MODULE FAILURE"
}`

**Comment by pierrejego** [comment]
The last errors came from an old version of pyOpenSSL on my debian8 server.
Just remove and reinstall a new one via pip (> 1.6.10)

`pip uninstall pyOpenSSL`

`pip install pyOpenSSL`

And everything works.

Thank you for the playbook, it's really quick to have a test environment for geOrchestra

**Comment by landryb** [comment]
Yeah, i know i have to update the playbook syntax for more recent ansible versions, it is sometimes a bit dated.
