### ISSUE TITLE
Géorchestra Catalogue (geonetwork) - erreur 404

### ISSUE THREAD

**Issue by marcfleck1** [georchestra/ansible#52]
Bonjour,

J'ai installé sur une debian 9 "vierge" georchestra avec ansible, apres quelques petits reglages, l'installation s'est effectuée sans encombre, je peux me connecter et voir toutes les pages, sauf Catalogue (geonetwork) qui m'affiche le "header" avec Erreur 404 - Ressource introuvable.
Je n'ai pas fait qu'un seul essai, j'ai a chaque fois le même résultat.
La seule modif faite dans le fichier yml est le nom fqdn de la machine.

Cordialement,
Marc Fleck
Unistra - Geographie

**Comment by fvanderbiest** [comment]
Merci de ce retour.
C'est déjà un miracle, car ce dépôt de contribution n'a pas été trop maintenu à jour de master !
On s'est promis d'y jeter un coup au geocom la semaine prochaine.

**Comment by marcfleck1** [comment]
Comme 1ere "réparation" je dirais qu'il manque déjà le /_static/ dans apache : 
/var/www/georchestra/conf/proxy.conf : 
<Proxy http://localhost:8180/_static/*>
    Require all granted
</Proxy>
ProxyPass /_static/ http://localhost:8180/_static/
ProxyPassReverse /_static/ http://localhost:8180/_static/

je pense que l'erreur est dans le fichier ansible/roles/apache/templates/common.conf.j2 ou la ligne {% if item.dest != '_static' %} me semble fausse, ca devrait plutot etre == et non pas !=  ... mais j'y connais pas grand chose a ansible.

Reste à savoir pourquoi j'ai dans les logs apache le "GET /geonework/ HTTP/1.1" 404

**Comment by landryb** [comment]
Je viens de mettre à jour un paquet de fichiers de config dans les différents roles/templates ansible pour être un peu plus à jour par rapport à master, et je n'ai pas de souci particulier pour accéder à geonetwork. Je n'ai pas encore regardé si les bouts de config apache avaien besoin d'adaptations....

Peux tu tenter une reconfiguration de ton instance, voir mieux, une réinstallation complète sur une machine vierge pour voir ce qu'il en est ? Est-ce que la webapp geonetwork avait correctement été déployée/démarrée ?

**Comment by marcfleck1** [comment]
Bonjour, je vais refaire une installation complète sur une debian toute neuve, des que j'ai un peu de temps (fin de cette semaine ou semaine prochaine)
Pour ce qui est de la webapp geonetwork, je n'ai pas remarque d'erreur à l'installation.
Je donnerai les résultats des que c'est fait.

**Comment by fvanderbiest** [comment]
Sans retour, je ferme.
