### ISSUE TITLE
Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/ansible#55]
TASK [postgresql : create georchestra user] ************************************
fatal: [mygeorchestra]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/var/tmp/ansible-tmp-1530692109.47-98572059002815/': Operation not permitted\nchown: changing ownership of '/var/tmp/ansible-tmp-1530692109.47-98572059002815/postgresql_user.py': Operation not permitted\n}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}

**Comment by landryb** [comment]
I've hit this one too, and i just need to remember how i worked around it..

**Comment by landryb** [comment]
Ah, now i remember: i hit it when sudo wasnt installed, which can happen if you run ansible-playbook -C to check for playbook validity. the task at the beginning of the psql role ensures sudo exists on the remote host.

**Comment by fvanderbiest** [comment]
Fixed with pipelining activated as per https://github.com/plone/ansible.plone_server/issues/86#issuecomment-226457346

**Comment by pmauduit** [comment]
You can also put the `allow_world_readable_tmpfiles` in the `ansible.cfg` configuration file:

```
allow_world_readable_tmpfiles=true
```

(I allowed myself to do so because I was in the vagrant proposed in the repository).

**Comment by guenhter** [comment]
Any update on this?

Turning on `allow_world_readable_tmpfiles` works perfectly fine, but I don't know if this should be the final solution though.

**Comment by landryb** [comment]
i dont really like it (as i dont understand it) but that's what @fvanderbiest did in https://github.com/georchestra/ansible/pull/70/commits/0132ae393bc581057e0dd5c5f937dec1b2da3bfc

**Comment by vincent-olivert-riera** [comment]
Make sure the `setfacl` tool (provided by the `acl` package) is installed on the remote host.

**Comment by gfnord** [comment]
For me the allow_world_readable_tmpfiles=true did not work but the installation of the package acl (and the tool setfacl) worked.

**Comment by landryb** [comment]
to me it really looks like kludges added on top of each other. for some reason tried with the acl package installed, and it didnt improve the situation... *shrug*

**Comment by alexanderadam** [comment]
> Make sure the `setfacl` tool (provided by the `acl` package) is installed on the remote host.

This worked. So the real issue is that Ansible doesn't show a proper message that would imply that the `acl` package is missing?

**Comment by pmauduit** [comment]
> to me it really looks like kludges added on top of each other. for some reason tried with the acl package installed, and it didnt improve the situation... _shrug_

it did for me on another context (testing another ansible playbook in a debian buster vagrant).

**Comment by ufukty** [comment]
> Make sure the `setfacl` tool (provided by the `acl` package) is installed on the remote host.

Apparently acl is removed from Ubuntu with 20.04 update. That could be the reason of error for the ones who upgrade their servers from 18.04 to 20.04.

**Comment by mpasternak** [comment]
Installing ``acl`` in 20.04 helps

**Comment by darkn3rd** [comment]
Apparently, there's also a need to create remote `$HOME/.ansible/tmp` directory on the remote system in addition to `acl` package.

```
[WARNING]: Module remote_tmp /home/agent/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as another user. To avoid this, create the remote_tmp dir with
the correct permissions manually
```

**Comment by vincent-olivert-riera** [comment]
> Apparently, there's also a need to create remote `$HOME/.ansible/tmp` directory on the remote system in addition to `acl` package.
> 
> ```
> [WARNING]: Module remote_tmp /home/agent/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as another user. To avoid this, create the remote_tmp dir with
> the correct permissions manually
> ```

@darkn3rd , no, you didn't not understand that error message.

It's telling you that `$HOME/.ansible/tmp` was created with the wrong permissions. If you delete it, that directory should be automatically created with the right permissions after you have installed `acl`.

**Comment by antonyh** [comment]
I accidentally uninstalled the `acl` package with Ansible: it removed it as an unwanted stray dependency. Adding it back in fixed the problem for me, once setfacl was available again.

**Comment by quangthe** [comment]
Ensure you install `acl` package as well
```
    - name: Install required packaged
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - acl
        - python3-pip
```

**Comment by vincent-olivert-riera** [comment]
> Ensure you install `acl` package as well
> 
> ```
>     - name: Install required packaged
>       apt:
>         name: "{{ item }}"
>         state: present
>       with_items:
>         - acl
>         - python3-pip
> ```

This issue was solved long time ago in a comment above: https://github.com/georchestra/ansible/issues/55#issuecomment-588313638

**Comment by FullofQuarks** [comment]
Adding on here that installing the `acl` package that includes `setfacl` solved my issue. Also on ubuntu 20.04

**Comment by landryb** [comment]
to all the people who commented here: thanks, but i seriously doubt you're actually using the code/playbooks in this repository. If you have issues with ansible itself in your own playbooks, please refer to the ansible documentation :)

**Comment by behnamhosseini** [comment]
I'm using ad-hoc and when I got into this problem, adding `-b --become-user ANSIBLE_USER` to my command fixes my problem. example:

`ansible all  -m file -a "path=/etc/s.text state=touch" -b --become-user ansadmin
`
**Of course, before this, I had given Sudo access to the user**
