### ISSUE TITLE
force-disable recaptcha check fails

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/ansible#57]
TASK [georchestra : force-disable recaptcha check] *****************************
fatal: [mygeorchestra]: FAILED! => {"changed": false, "msg": "Path /srv/tomcat/georchestra/webapps/console/WEB-INF/views/validation.jsp does not exist !", "rc": 257}

**Comment by landryb** [comment]
I know, need to add a `wait_for` task that waits for the tomcat to have unpacked the console war..
