### ISSUE TITLE
[ Configuration ] SQL urls

### ISSUE THREAD

**Issue by pierrejego** [georchestra/ansible#61]
Hi,
on geochestra master SQL filenames have changed. This has an impact on configuration. [Postgresql configuration](https://github.com/georchestra/ansible/blob/master/roles/postgresql/vars/main.yml)

 - https://raw.github.com/georchestra/georchestra/master/postgresql/02-mapfishapp.sql
  - https://raw.github.com/georchestra/georchestra/master/postgresql/04-console.sql
  - https://raw.github.com/georchestra/georchestra/master/postgresql/06-ogc-server-statistics.sql
  - https://raw.github.com/georchestra/georchestra/master/postgresql/07-atlas.sql
  - https://raw.github.com/georchestra/georchestra/master/postgresql/08-geofence.sql
  - https://raw.github.com/georchestra/georchestra/master/postgresql/09-extractor-app.sql

could be replace by

 - https://raw.github.com/georchestra/georchestra/master/postgresql/020-mapfishapp.sql
  - https://raw.github.com/georchestra/georchestra/master/postgresql/040-console.sql
  - https://raw.github.com/georchestra/georchestra/master/postgresql/060-ogc-server-statistics.sql
  - https://raw.github.com/georchestra/georchestra/master/postgresql/070-atlas.sql
  - https://raw.github.com/georchestra/georchestra/master/postgresql/080-geofence.sql
  - https://raw.github.com/georchestra/georchestra/master/postgresql/090-extractor-app.sql

Not tried yet.

Regards

**Comment by landryb** [comment]
myyyeah i knew i had to change something when i saw georchestra/georchestra@4af06f6b5b but didnt remember why.. thanks !

**Comment by pierrejego** [comment]
Hello,
I can also see an impact  [here](https://github.com/georchestra/ansible/blob/b43592652a84ed58912bca4235ab5fa220653aac/roles/postgresql/tasks/other_schemas.yml#L32)

we can find four occurences of 05-console-data.sql in the task to be replace by 041-console-data.sql

Regards
