### ISSUE TITLE
upgrade cadastrapp

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/ansible#63]
https://packages.georchestra.org/debian/pool/main/g/georchestra-cadastrapp/ features 1.7 while we currently offer 1.3 by default: https://github.com/georchestra/ansible/blob/7f5ebb7ff668e270daadee95678bed3505fbee9c/playbooks/georchestra.yml#L27

**Comment by landryb** [comment]
Sure, and we even only offer a deb coming from a local src via scp, cf https://github.com/georchestra/ansible/blob/master/roles/georchestra/tasks/war_cadastrapp.yml :)
