### ISSUE TITLE
cadastrapp - missing tables

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/ansible#67]
To run cadastrapp master, several tables are missing, eg `script/commun/tables/prop_type_filiation.sql`.

Tentative fix on 18.06 branch with https://github.com/georchestra/ansible/commit/ec444564344546b4f232c295ace17c56431a4247

This is related with https://github.com/georchestra/cadastrapp/commit/590b603689776374c3c995e8ca5788d15178c8ed

**Comment by landryb** [comment]
fixed by ec44456 which was merged a while ago ?
