### ISSUE TITLE
Could not find the requested service tomcat@...

### ISSUE THREAD

**Issue by makinetoshe** [georchestra/ansible#72]
Hello,

I'm trying to deploy georchestra via ansible but I still get this message at the end of the script:

failed: [mygeorchestra] (item=dict_keys(['proxycas', 'georchestra', 'geoserver'])) => {"changed": false, "item": "dict_keys(['proxycas', 'georchestra', 'geoserver'])", "msg": "Could not find the requested service tomcat@dict_keys(['proxycas', 'georchestra', 'geoserver']): host"}

I have the impression that the tomcat services have not been created but I have no error message to that effect. Where did I get it wrong?
Thank you in advance for your help.

Mak '

**Comment by landryb** [comment]
nah, that's probably because you use ansible with python3, i recently hit the same issue and fixed it by replacing `tomcat_instances.keys()` everywhere with ` tomcat_instances|list `. Will push a fix soonish..

**Comment by makinetoshe** [comment]
Thank you so much !
This was the cause of my crash. I modified the files and the installation was successful.
It works but I now have an error "appMinorVersionSupported" going back to the catalog tab, I will look at that.
Thanks again.
