### ISSUE TITLE
[runtime_exception] Failed to compile stylesheet

### ISSUE THREAD

**Issue by makinetoshe** [georchestra/ansible#73]
Hello friends,

I deployed georchestra via last ansible scripts. The deployment is correctly carried out :)

However I have a problem when I use catalog.edit, I get this error:
**runtime_exception** Failed to compile stylesheet. 8 errors detected.TransformerConfigurationException

![image](https://user-images.githubusercontent.com/69341983/90031247-4c953d00-dcbd-11ea-8d26-d1b4cfbcf955.png)

Could you help me please ?
Thank you in advance for your help.

Mak '

**Comment by RemiDesgrange** [comment]
Maybe you forgot to init a submodule in geonetwork (`git submobule update --init --recursive`)

**Comment by makinetoshe** [comment]
Thank you for your prompt response !
So I need to run this command on my Ansible server before relaunching the deployment script?

**Comment by RemiDesgrange** [comment]
First try it without ansible to see if it work. Ansible playbook should work out of the box, if not we should know what to fix :-)

**Comment by makinetoshe** [comment]
I modified the file /etc/georchestra/geonetwork/geonetwork.properties :

# geonetwork.schema.dir = $ {geonetwork.config.dir} / schema_plugins /
geonetwork.schema.dir = / srv / tomcat / georchestra / webapps / geonetwork / WEB-INF / data / config / schema_plugins

This works now
