### ISSUE TITLE
[services] geoserver/web

### ISSUE THREAD

**Issue by makinetoshe** [georchestra/ansible#74]
Bonjour,

J'ai déployé georchestra via ansible.
J'ai un souci dans l'interface GeoServer (https://xxxxxx/geoserver/web/).
Lorsque je navigue dans les onglets ou en cliquant sur les boutons, j'obtiens une erreur 400.
```
État HTTP 400 – Requête invalide
Type Rapport d'état
message Origin does not correspond to request
description La requête envoyée par le client était syntaxiquement incorrecte.
Apache Tomcat/9.0.31 (Debian)
```
A chaque fois c'est une url du style xxxxxxPage?48-1.ILinkListener-charts-tabs~container-tabs-2-link qui est générée et cause l'erreur.

Auriez-vous une piste pour cerner le pb ?
Merci

Georges.

**Comment by fvanderbiest** [comment]
Bonjour, Quelle branche du dépôt ? 20.x ou master ?

**Comment by makinetoshe** [comment]
Bonjour,

Il s'agit de la 20.x
Je vous remercie.

**Comment by landryb** [comment]
j'ai aussi vu ce bug, et je crois que ca a été corrigé une fois appliqué https://github.com/georchestra/georchestra/blob/20.0.0/migrations/20.0/README.md#tomcat-for-geoserver localement. Si ca corrige le problème pour toi, pull request welcome pour le fixer dans le role ansible tomcat..

**Comment by makinetoshe** [comment]
Merci. J'ai appliqué ce correctif mais malheureusement résultat identique :(
De plus il me semble que les modifs demandées étaient déjà présentes dans ma configuration (?)
Je cherche de ce fait les info de Rewrite sur les requêtes uri spécifiques à Geoserver mais sans succès pour le moment...

**Comment by landryb** [comment]
meme après redémarrage du service `tomcat@geoserver` ?

**Comment by makinetoshe** [comment]
Oui, j'ai complètement redémarré le serveur.
J'ai peut-être mal fait quelque-chose mais chaque étape a été validée sans souci particulier.
Cependant une chose m'échappe, dans ce correctif il semble que le problème se pose au niveau de la brique "console" et non "geoserver" ? ->
```
RewriteCond %{REQUEST_URI} !^/console/manager/public/.*$
RewriteCond %{REQUEST_URI} ^/console/manager/([home|users|org|orgs|role|roles|logs|analytics|delegations].*)$
RewriteRule .* /console/manager/#!/%1 [NE,R,L]
```

**Comment by makinetoshe** [comment]
J'ai refait, à tête reposée, la démarche mais toujours le même souci. J'ai bien vérifié en détail les différences dans les fichiers de [config](https://gist.github.com/fvanderbiest/e3afb00cd47a406cddaa2991d7171d01) et tout était déjà au format 20.0...
Je suis d’ailleurs parti de la 20.0 avec ansible.
Une autre piste ?
Merci !

**Comment by fvanderbiest** [comment]
Je reproduis en effet avec vagrant dans la branche 20.x 

Sur la page https://georchestra.example.org/geoserver/web/wicket/bookmarkable/org.geoserver.gwc.web.wmts.WMTSAdminPage je change une valeur, je sauve, et j'arrive sur https://georchestra.example.org/geoserver/web/wicket/bookmarkable/org.geoserver.gwc.web.wmts.WMTSAdminPage?20-2.IFormSubmitListener-form

Erreur 400 "La requête envoyée par le client était syntaxiquement incorrecte."

**Comment by fvanderbiest** [comment]
Pour vérifier si c'était corrigé sur master, j'ai testé la branche master.
Mais étonnamment, sur master, on a un vieux geoserver 2.15 qui ne présente pas l'erreur.
Il doit y avoir une erreur sur les paquets tirés.

**Comment by makinetoshe** [comment]
Pour info j'ai un geoserver 2.16.1

**Comment by makinetoshe** [comment]
Y aura-t'il un correctif ?
Est-il possible de repasser en 2.15 ?

**Comment by fvanderbiest** [comment]
> Y aura-t'il un correctif ?

En mode "best effort" communautaire, car nous ne reproduisons pas dans nos environnements de production.
Si vous souhaitez une correction rapide, je vous invite à contacter l'une ou l'autre des sociétés offrant du service sur geOrchestra.

> Est-il possible de repasser en 2.15 ?

Oui. Vous pouvez également utiliser un GeoServer récent non geOrchestra, pourvu que vous conserviez le datadir d'un geoserver geOrchestra (https://github.com/georchestra/geoserver_minimal_datadir/tree/20.0 pour la branche des releases 20.0.x sans geofence), de manière à ce que les filtres chargés de la lecture des headers du SP et des informations du LDAP soient correctement configurés.

**Comment by makinetoshe** [comment]
Merci pour ces infos

**Comment by landryb** [comment]
En fait je pense que la 'bonne' correction pour ce problème est https://github.com/georchestra/georchestra/blob/master/docs/setup/tomcat.md#in-case-of-troubles-with-the-geoserver-ui, que j'ai corrigé localement en ajoutant `"-DGEOSERVER_CSRF_WHITELIST={{ georchestra_fqdn }}"` aux JAVA_OPTS parce que je trouve ca très moche de bricoler web.xml.

**Comment by landryb** [comment]
Cf https://osgeo-org.atlassian.net/browse/GEOS-9353 pour d'autres pistes ?

**Comment by makinetoshe** [comment]
C'est corrigé ! Merci beaucoup !
Effectivement lié à  https://github.com/georchestra/georchestra/blob/master/docs/setup/tomcat.md#in-case-of-troubles-with-the-geoserver-ui
Pour le moment j'ai modifié le fichier web.xml pour faire vite, je regarderai pour utiliser JAVA_OPTS.

Je clôture ce ticket :)

**Comment by fvanderbiest** [comment]
Thanks Landry for the commit !
