### ISSUE TITLE
Geoserver 404 and datafeeder unavailable

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/ansible#79]
I'd installed georchestra locally  from master branch.

To do that, i use WLS debian 10 to trigger georchestra/ansible playbook and install georchestra into local VM - debian 10 (SSH access).

- Mapfishapp, Console, GeoNetwork, authent with testadmin seems works.
- GeoServer return 404
- datafeeder Connection refused
https://georchestra.example.org/mapfishapp/
![image](https://user-images.githubusercontent.com/16317988/122222413-87a26700-ceb2-11eb-9b22-a071621169a3.png)

https://georchestra.example.org/geoserver/web/

![image](https://user-images.githubusercontent.com/16317988/122222504-a0128180-ceb2-11eb-8ed1-335c096433cb.png)

**Comment by Gaetanbrl** [comment]
I don't remember some missing steps .... maybe about certificates or PostGis missing ?

**Comment by Gaetanbrl** [comment]
Some logs :

* /srv/logs

`sec-proxy.log`

```
2021-06-16 15:09:27 security [ERROR] Exception occured when trying to connect to the remote url 'http://localhost:8480/datafeeder/'
java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at org.georchestra.security.Proxy.executeHttpRequest(Proxy.java:810)
```
-------
```
2021-06-16 15:10:40 statistics [INFO] testadmin|2021/06/16 15:10:40|http://localhost:8380/geoserver/web|Project Steering Committee|ROLE_SUPERUSER,ROLE_MAPSTORE_ADMIN,ROLE_USER,ROLE_ADMINISTRATOR,ROLE_CKAN_SYSADMIN,ROLE_EXTRACTORAPP,ROLE_GN_ADMIN,ROLE_EMAILPROXY
2021-06-16 15:10:40 security [WARN] Downstream server returned a status code which could be an error. Statuscode: 404, reason: 

```

no more sec-proxy.log about mapstore.

**Comment by pmauduit** [comment]
the first one is a known bug because of 2 different servlet filters defined in the GS war, thanks to the CORS handling configuration: https://github.com/georchestra/georchestra/issues/3358

the DF ui "should" be available under the `/import/` URI. the `/datafeeder` even if defined in the targets-mapping.properties might not redirect to the swagger-ui by default.

**Comment by Gaetanbrl** [comment]
> the DF ui "should" be available under the /import/ URI. the /datafeeder even if defined in the targets-mapping.properties might not redirect to the swagger-ui by default.

I have completely forget to check the targets-mapping ... thanks.

Well, `/import/` seems better, but  i get a perfect blue empty page now. Need to check the datafeeder install...

![image](https://user-images.githubusercontent.com/16317988/122235122-bb36be80-cebd-11eb-9dc3-b7ca40648e61.png)

**Comment by pmauduit** [comment]
I'd expect some errors client-side that you should be more able than me to debug ;-)

Also: one of the requirements for the DF to function properly is to first make sure a thesaurus (geonetwork-side) is correctly loaded. If you load an inspire-theme from the registry, then the default DF configuration should be ok.

**Comment by Gaetanbrl** [comment]
> the first one is a known bug because of 2 different servlet filters defined in the GS war

thanks @pmauduit ! GS start now (tomcat).

I will update Ansible doc to keep this point in mind.
