### ISSUE TITLE
Mapstore2 - no target-mapping entry 

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/ansible#83]
Missing target-mapping entry for mapstore and masptore/ return 404 but seems deploy.

```
nano security-proxy/targets-mapping.properties`
mapstore=http://localhost:8280/mapstore/
```

Works fine now (with above errors).

I will insert this entry in ansible template and create PR.

**Comment by landryb** [comment]
cf https://github.com/georchestra/ansible/blob/master/roles/georchestra/templates/security-proxy/targets-mapping.properties.j2, as mapstore isnt in the struct being looped on this was probably forgotten
