### ISSUE TITLE
[ Mapstore ] Datadir 

### ISSUE THREAD

**Issue by pierrejego** [georchestra/ansible#91]
https://docs.georchestra.geo-solutions.it/en/latest/configuration/application/index.html#advanced-map-viewer-configuration
https://docs.georchestra.geo-solutions.it/en/latest/configuration/application/index.html#read-write-configuration-directory

We should have two datadir, one static, one dynamic as geoNetwork could have. 
One for the configuration, the other one to push data from mapstore (Extension)

**Comment by landryb** [comment]
there's `/srv/data` already for geonetwork/geoserver datadirs, so maybe `/srv/data/mapstore` ? I dont use the read-write mapstore datadir as i deploy extensions manually in the georchestra datadir as root.

**Comment by pierrejego** [comment]
Already done  -

Extension explained here : https://github.com/georchestra/ansible#additional-config
Config here : https://github.com/georchestra/ansible/blob/master/roles/georchestra/tasks/config.yml#L41
